### ISSUE TITLE
Issue with ConversationMetaUpdate

### ISSUE THREAD

**Issue by baptistejamin** [crisp-im/go-crisp-api#1]
Updating a meta with a results empty nested methods.

omit empty flags are not seeming to work on nested structures and results valid, but empty geolocation, browser.

Suggest to replace func UpdateConversationMetas with UpdateConversationMetas(websiteID string, sessionID string, metas interface{}) to allow developers to override with their own structures.

**Comment by valeriansaliou** [comment]
It does work if left empty, actually. Tested previously and worked fine. If no value is passed and omit empty is set, the empty key will never be marshalled, as expected. Only issue I see is that it cannot be used to reset a value to blank, as "" will be considered empty and thus key not set.
