### ISSUE TITLE
documentation errors

### ISSUE THREAD

**Issue by ghost** [crisp-im/go-crisp-api#3]
```
server/server.go:182: client.UserAccountCreate undefined (type *crisp.Client has no field or method UserAccountCreate)
```

**Comment by valeriansaliou** [comment]
Hi!

Thanks for your reports! If you refer to the docs - which I just enhanced to make them clear, you'll see that methods are namespaced and accessed via your `client` instance, and the structures are accessed directly from `crisp`.

Thus, `client.UserAccountCreate` should be `crisp.UserAccountCreate`.

**Comment by ghost** [comment]
thanks. just switching over from intercom.io and trying to figure out your api. Also would be helpful is there were a way to create a user via the api (with user sign up or email list sign up)

**Comment by valeriansaliou** [comment]
Cool! Let me know if we can improve on anything on this lib. You can manage users via the People namespace, there should be a CreateProfile method on People (I don't have an eye on the docs ATM).
