### ISSUE TITLE
Crisp side cant preview img or video thumbnail when i send it from telegram

### ISSUE THREAD

**Issue by selfmakeit** [crisp-im/go-crisp-api#9]
here is my code demo:
`if update.Message.Video != nil {
		file,err := bot.GetFileDirectURL(update.Message.Video.FileID)
		if err == nil {
			client.Website.SendFileMessageInConversation(msgInfo.WebsiteID, msgInfo.SessionID, crisp.ConversationFileMessageNew{
				Type:   "file",
				From:   "operator",
				Origin: "chat",
				Content: crisp.ConversationFileMessageNewContent{
					Name: "video.mp4",
					Type: update.Message.Video.MimeType,
					URL:  file,
				},
			})
		}
	}`

**Comment by valeriansaliou** [comment]
Can you ask that over Crisp Support? It looks like it isn’t related to the Go wrapper.
